server:
  port: 8081
one:
  name: abc
  start: 8888-12-10
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9091,localhost:9092,localhost:9093,localhost:9094,localhost:9095