server:
  port: 8082
spring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
  task:
    scheduling:
      pool:
        size: 10
feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 50000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 70000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000