server:
  port: 8082
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  task:
    scheduling:
      pool:
        size: 10
feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 50000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 70000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000